### ISSUE TITLE
Documentation issue - translators

### ISSUE THREAD

**Issue by lprimak** [trsvax/tapestry-datepicker#5]
In the documentation, its confusing how to add translators.

If you copy and paste translator code, it will not work,
because instead of configuration.add() configuration.override() needs to be there.
Exceptions resulting from this are confusing, and its not easy to figure out what's going wrong.

**Comment by lprimak** [comment]
Project no longer maintained

**Comment by trsvax** [comment]
Sorry I never noticed this issue. I'm not sure what you mean by this comment. The examples are configurations included in the package. If you want to override them you do need configuration.override(). I believe this is also in the readme. As far as the error goes if this is a Tapestry registry error there is not much I can do about that

**Comment by lprimak** [comment]
I no longer maintain the project this is an issue with, i.e. no longer interested in a fix.
Thanks for your hard work
